data:
  train_dir: "dataset/train"
  csv_path: "dataset/trainset_meta_info.csv"
  img_size: 224
  batch_size: 32
  num_workers: 4

model:
  name: "mobilenet_v3_small"
  num_classes: 5
  pretrained: true

training:
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 5

augmentation:
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
  rotation: 30
  scale: [0.8, 1.2] 